version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres_container
    environment:
      POSTGRES_DB: dummy
      POSTGRES_USER: postgresAdmin
      POSTGRES_PASSWORD: postgresPassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
